require 'fileutils'
task :post do
	title = ENV['title'] || "new-post"
	tags = ENV['tags'] || ''
	make_img_dir = ENV['imgdir'] || false
	date = (ENV['date'] ? Time.parse(ENV['date']) : Time.now).strftime('%Y-%m-%d')
	filename = File.join('.', "#{Time.now.strftime('%Y-%m-%d')}-#{title.strip.gsub(' ', '-').gsub(/[^\w-]/, '')}.markdown")
	open(filename, 'w') do |post|
		post.puts "---"
		post.puts "layout: default"
		post.puts "title: \"#{title}\""
		post.puts "date: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
		post.puts "categories: "
		post.puts "---"
		post.puts "\nYour content here."
		if make_img_dir
			img_dir = File.basename(filename.chomp(File.extname(filename)))
			FileUtils.mkdir_p("../images/posts/#{img_dir}")
			post.puts "\n" * 5
			post.puts "[imgdir]: /images/posts/#{img_dir}/"
		end
	end
end

